language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t giladk1221/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true giladk1221/docker-react npm run test